# For simulating Ray's raman soliton, the temporal span need to be around 100ps, 2**14 grid point for enough frequency span
# In all cases the input pulse profile is E = exp(-(t_sample/2e-12)**2)

"""Max's cavity parameter"""

# cavity params 
F = 200 # real finesse is 400 but reduced to 200 to reduce tail generated by desync 
theta = .01 
gamma = 1.8e-3 

# dispersion 
# at zero-dispersion 
b3_zdw = 1.2949475e-40
b4_zdw = -6.659178e-55
b5_zdw = 0e-71
zdw = 1564.5221e-9

# at 1490 nm 
disp = {2: 6.594155731164429e-27, 3: 8.936754960752639e-41, 4: -6.659178e-55}

# at 1550 nm 
disp = {2: 1.419311926025424e-27, 3: 1.219778673652613e-40, 4: -6.659178e-55}

# Ray's Raman soliton
# if uses 0.5 m as cavity length 
L = 0.5; P_in = 20; delta  = 0.03; d = -85e-15 
# if uses 1 m as cavity length
L = 1; P_in = 25; delta = 0.03; d = -170e-15 

# Max's Raman soliton 
L = 5; F = 400; delta = 0.03; d = 130e-15; P_in = 15

"""Ray's Cavity parameter"""
# cavity params
gamma = 3e-3
F = 200
theta = 0.013 

# dispersion at 1550 
disp = {2: 7.5 * (1e-12)**2 * (1e-3), 3: 0.16 * (1e-12)**3 * (1e-3), 4: 0}

# Ray's Raman soliton 
L = 0.5; P_in = 18; d = -75e-15 
L = 1; P_in = 18; d = -145e-15
L = 2; P_in = 18; d = -280e-15 
